### PR TITLE
set redirect to true by default, redesign pend and declines

### PR DESCRIPTION
**Pull request by bakedbean**
also adds a test button for the API Gateway that handles backend interactions for the dev store

### CODE REVIEW

**Comment by TheJohnzo** [comment]
I'm getting errors with the new button layout (this was after fresh `yarn build`): 
image

**Comment by widox** [comment]
When I click the new big "Send Test AWS..." button, the request gets a 404. is that expected?

**Comment by bakedbean** [comment]
yes, for now

**Comment by bakedbean** [comment]
> I'm getting errors with the new button layout (this was after fresh `yarn build`):
> image

I am not seeing this, can you confirm you are using Node >= 13?

**Comment by widox** [comment]
> I'm getting errors with the new button layout (this was after fresh `yarn build`):
> ![image](https://user-images.githubusercontent.com/9207494/129365836-77f465e1-e1e7-42c6-96e6-0092c20a4ab6.png)

also seeing this. looks like the payload is wonky
`merchant_data: "redirect"`

and in puma output
```
Exception Notification:

#<NoMethodError: undefined method `keys' for "redirect":String>                                                                                                                                                                                                                                    undefined method `keys' for "redirect":String
Backtrace:
[
[ 0] "/Users/ckmatt/projects/ck-web/ck-web/app/controllers/api/ecomm_controller.rb:366:in `set_merchant_data'",
```

**Comment by bakedbean** [comment]
> > I'm getting errors with the new button layout (this was after fresh `yarn build`):
> > ![image](https://user-images.githubusercontent.com/9207494/129365836-77f465e1-e1e7-42c6-96e6-0092c20a4ab6.png)
> 
> also seeing this. looks like the payload is wonky
> `merchant_data: "redirect"`
> 
> and in puma output
> 
> ```
> Exception Notification:
> 
> #<NoMethodError: undefined method `keys' for "redirect":String>                                                                                                                                                                                                                                    undefined method `keys' for "redirect":String
> Backtrace:
> [
> [ 0] "/Users/ckmatt/projects/ck-web/ck-web/app/controllers/api/ecomm_controller.rb:366:in `set_merchant_data'",
> ```

How are you seeing that?  What are the steps to reproduce?

**Comment by widox** [comment]
> > > I'm getting errors with the new button layout (this was after fresh `yarn build`):
> > > ![image](https://user-images.githubusercontent.com/9207494/129365836-77f465e1-e1e7-42c6-96e6-0092c20a4ab6.png)
> > 
> > 
> > also seeing this. looks like the payload is wonky
> > `merchant_data: "redirect"`
> > and in puma output
> > ```
> > Exception Notification:
> > 
> > #<NoMethodError: undefined method `keys' for "redirect":String>                                                                                                                                                                                                                                    undefined method `keys' for "redirect":String
> > Backtrace:
> > [
> > [ 0] "/Users/ckmatt/projects/ck-web/ck-web/app/controllers/api/ecomm_controller.rb:366:in `set_merchant_data'",
> > ```
> 
> How are you seeing that? What are the steps to reproduce?

I'm just loading up `http://localhost:3000/dev` in a new private window and clicking any of the pending/decline options

**Pull request merged**
